<!DOCTYPE html>
<html lang="PT_BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Desafio</title>


    <script class="">

   

throw new Error('Houve um erro mas não se preocupem iremos trabalhar em cima disso')

  let video = Array()


  video[1] = Array()


  video[1]['nome'] = 'Naruto Shippuden'
  
  video[1]['Categoria'] = 'Anime'


function getVideo(video) {
  //lógica

try {
    console.log(video[0]['nome'])


 
} catch(erro) {

console.log(erro)
    console.log('reagiu')
    throw new Error('Houve um erro mas não se preocupem iremos trabalhar em cima disso')
   // throw new Erro força a travar toda a aplicação sequencial try-catch-finally



} finally {

   console.log('Sempre passa por aqui... pode ser aplicado para o (try e catch)')



}





console.log('Não morreu a aplicação')
}

getVideo(video)

        
           </script>
        


</head>
<body>



  
</body>
</html>